Run shellcheck on all bash code
containers/kubensmnt pull request #6
Opened 2022-07-21 13:29 UTC by lack

Signed-off-by: Jim Ramsay <jramsay@redhat.com>

2022-07-21 18:39 UTC, lack commented
@Miciah: This should address all your comments on the `kubensenter` script from https://github.com/openshift/kubernetes/pull/1327

Once this is merged I'll release v1.1.2 from this repo and import it there.

2022-07-22 14:15 UTC, sakhoury requested changes

2022-07-22 14:15 UTC, sakhoury commented on test/library-integration.bats
> +    # Ensure the test binaries (build alongside this file) are in the path
Update comment: `...(build alongside ...)..` to `...(built alongside ...)..`

2022-07-22 14:15 UTC, sakhoury commented on test/utils.sh
> +    # Set up a not-a-mount namespace for negative tests
Update comment: `... not-a-mount ...` to `... non-mount ...`

2022-07-22 14:15 UTC, sakhoury commented on utils/kubensenter/kubensenter
> +    echo 'If $KUBENSMNT is set in the environment, skip autodetectipn and attempt to join'
`autodetectipn` to `autodetection'

2022-07-22 14:44 UTC, sakhoury approved these changes
\lgtm

2022-07-22 14:46 UTC, merged